package router

import (
	"flower-lottery-backend/config"
	"flower-lottery-backend/controller"
	"flower-lottery-backend/middleware"
	tokenjwt "flower-lottery-backend/pkg/jwt"
	"flower-lottery-backend/repository"
	"flower-lottery-backend/service"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

func New(db *gorm.DB, log *zap.Logger, cfg *config.Config) *gin.Engine {
	r := gin.New()
	r.Use(middleware.RequestLogger(log), middleware.Recovery(log))
	r.MaxMultipartMemory = 8 << 20
	r.Static("/uploads", cfg.Storage.UploadDir)
	tokens := tokenjwt.New(cfg.JWT)
	avatars := service.NewAvatarService(cfg.Storage.UploadDir)
	auth := controller.NewAuthController(service.NewAuthService(repository.NewUserRepository(db), tokens), avatars)
	wallet := controller.NewWalletController(service.NewWalletService(repository.NewWalletRepository(db)))
	gameRepository := repository.NewGameRepository(db)
	announcementHub := service.NewRewardAnnouncementHub(gameRepository, log)
	poolConfigHub := service.NewPoolConfigHub()
	game := controller.NewGameController(service.NewGameService(gameRepository), announcementHub, poolConfigHub)
	adminController := controller.NewAdminController(db, cfg.JWT, poolConfigHub)
	health := controller.HealthController{DB: db}
	v1 := r.Group("/api/v1")
	v1.GET("/health", health.Check)
	v1.POST("/auth/register", auth.Register)
	v1.POST("/auth/login", auth.Login)
	v1.POST("/auth/refresh", auth.Refresh)
	v1.GET("/reward-announcements/stream", game.RewardAnnouncements)
	v1.GET("/pool-config/stream", game.PoolConfigUpdates)
	protected := v1.Group("")
	protected.Use(middleware.UserAuth(tokens))
	protected.POST("/auth/logout", auth.Logout)
	protected.GET("/me", auth.Me)
	protected.PATCH("/me", auth.UpdateProfile)
	protected.POST("/me/avatar", auth.UploadAvatar)
	protected.PUT("/me/password", auth.ChangePassword)
	protected.GET("/wallet", wallet.Get)
	protected.GET("/wallet/exchange-options", wallet.Options)
	protected.POST("/wallet/exchanges", wallet.Exchange)
	protected.GET("/wallet/petal-gift-pack", wallet.PetalGiftPackStatus)
	protected.POST("/wallet/petal-gift-pack", wallet.PurchasePetalGiftPack)
	protected.GET("/wallet/transactions", wallet.Transactions)
	protected.GET("/activities/current/home", game.Home)
	protected.GET("/activities/current/pools", game.Pools)
	protected.GET("/activities/current/content", game.ActivityContent)
	protected.GET("/activities/current/rewards/catalog", game.Catalog)
	protected.POST("/lottery/orders", game.Draw)
	protected.POST("/lottery/draws/:id/select", game.SelectLotteryReward)
	protected.GET("/lottery/orders", game.Orders)
	protected.GET("/lottery/records", game.LotteryHistory)
	protected.GET("/lottery/rewards", game.LotteryRewards)
	protected.POST("/lottery/preview-orders", game.Preview)
	protected.POST("/lottery/preview-orders/:id/confirm", game.ConfirmPreview)
	protected.POST("/lottery/preview-orders/:id/cancel", game.CancelPreview)
	protected.GET("/flower/round", game.Home)
	protected.POST("/flower/chests/:id/open", game.OpenChest)
	protected.POST("/flower/chests/:id/select", game.SelectChest)
	protected.GET("/flower/chests/records", game.ChestHistory)
	protected.POST("/flower/stage-rewards/:id/claim", game.ClaimStage)
	protected.POST("/flower/round/next", game.NextRound)
	protected.GET("/rewards", game.Rewards)
	protected.GET("/leaderboard", game.Leaderboard)
	admin := v1.Group("/admin")
	admin.POST("/auth/login", adminController.Login)
	admin.Use(middleware.AdminAuth(tokens))
	admin.GET("/me", adminController.Me)
	admin.GET("/dashboard", adminController.Dashboard)
	admin.GET("/users", adminController.Users)
	admin.POST("/users", adminController.CreateUser)
	admin.PATCH("/users/:id", adminController.UpdateUser)
	admin.DELETE("/users/:id", adminController.DeleteUser)
	admin.POST("/users/:id/assets", adminController.AdjustUserAsset)
	admin.GET("/asset-transactions", adminController.Assets)
	admin.GET("/activities", adminController.Activities)
	admin.PATCH("/activities/:id", adminController.UpdateActivity)
	admin.GET("/activities/:id/content", adminController.ActivityContent)
	admin.PUT("/activities/:id/content", adminController.UpdateActivityContent)
	admin.GET("/exchange-options", adminController.ExchangeOptions)
	admin.POST("/exchange-options", adminController.CreateExchangeOption)
	admin.PATCH("/exchange-options/:id", adminController.UpdateExchangeOption)
	admin.DELETE("/exchange-options/:id", adminController.DeleteExchangeOption)
	admin.GET("/pools", adminController.Pools)
	admin.GET("/pools/:id/config", adminController.PoolConfig)
	admin.PUT("/pools/:id/config", adminController.UpdatePoolConfig)
	admin.GET("/reward-items", adminController.RewardItems)
	admin.POST("/reward-items", adminController.CreateRewardItem)
	admin.PATCH("/reward-items/:id", adminController.UpdateRewardItem)
	admin.DELETE("/reward-items/:id", adminController.DeleteRewardItem)
	admin.GET("/lottery-orders", adminController.Orders)
	admin.GET("/rewards", adminController.Rewards)
	admin.GET("/rounds", adminController.Rounds)
	admin.GET("/leaderboard", adminController.Leaderboard)
	admin.GET("/operation-logs", adminController.OperationLogs)
	return r
}
